### PR TITLE
This is just plain bullsh*t

### PR DESCRIPTION
**Pull request by crackcomm**

### CODE REVIEW

**Comment by dgryski** [comment]
Regardless of the validity of the complaint, it is an accurate representation of the issue raised in the article.

**Comment by crackcomm** [comment]
I may just not be experienced enough to understand this issue.

> You end up with what look like run-on sentences 

Yes indeed if you interpret Go code as C++ code, it may look like that.
I think it's easier to see a dot on the end where it shouldn't be than to see a missing semicolon or a dot instead of semicolon.

**Comment by crackcomm** [comment]
Also "no this" it's almost not true.

**Comment by crackcomm** [comment]
And "has pointers" makes me laugh.

**Comment by parkr** [comment]
@crackcomm If you're arguing against the article, then you should really bring it up with the author. This repository simply keeps track of the articles and their arguments. This repository is not making any of these arguments. Please close this PR.

**Comment by crackcomm** [comment]
Yea then let's not review this repo at all.

**Comment by ksimka** [comment]
@crackcomm Yes, some arguments look weird for me too, but authors can have their own opinion. Almost every blog listed here has comments, so you can follow the link and express your dissatisfaction personally.

**Pull request closed without merging**
