### PR TITLE
Add generator with reverse index

### PR DESCRIPTION
**Pull request by capoferro**
I added a generator so the reverse index doesn't require maintenance.

### CODE REVIEW

**Comment by ksimka** [comment]
Cool, but can you please fix it? Look at the diff, it's broken.

**Comment by capoferro** [comment]
Looks like I inadvertantly deleted a ` on one of the strings. Fixed now.

**Comment by ksimka** [comment]
Thanks, will look into it a bit later, have to resolve conflicts.

**Comment by capoferro** [comment]
@ksimka I've rebased and ensured that all the new entries are now in the json.

**Comment by ksimka** [comment]
Wow, thanks, man, I was too busy last days. Looks good.

**Pull request merged**
